### ISSUE TITLE
make star one hour of videos watched

### ISSUE THREAD

**Issue by Raehale** [Raehale/progress-board#11]
For every hour watched, add a star to the Live Achievements section

**Comment by vrhernandez** [comment]
I can take this one!

**Comment by vrhernandez** [comment]
just checking, this is referencing the counter for Videos watched?

**Comment by vrhernandez** [comment]
this is waiting for the timer functionality

**Comment by vrhernandez** [comment]
duplicate issue, this is part of another existing issue
