### ISSUE TITLE
body { margin: 0 }

### ISSUE THREAD

**Issue by Samcraig77** [Raehale/progress-board#95]
I've noticed we don't have the usual body { margin: 0 } CSS code. on smaller screens this is making a slight horizontal scroll possible, when it doesn't seem to have any content there. Is this intended?

**Comment by fame372** [comment]
Hi sam, I looked at this and you are right. we need to add the {margin :0} do you want to do it since you are the one who noticed it? thank you

**Comment by Samcraig77** [comment]
For sure!
